config/routes.rb
Rails.application.routes.draw do
  resources :gamegenres
  resources :gamegenres
  resources :gamegenres
  root :to => redirect('/gamegenres')
  get '/gamegenres/:id', to: 'gamegenres#search_genres', as: 'search_genres'
  get '/search' => 'gamegenres#search', :as => 'search_page'

end

app/models/gamegenre.rb
class Gamegenre < ActiveRecord::Base
    def self.get_other_genres(difficulty)
        @difficulty = Gamegenre.where(difficulty:difficulty)
        if @difficulty.blank?
        return "No Genre with this difficulty"
        else
        return @difficulty
        end
    end

    def self.same_genre title
    Gamegenre.where(:title => title)
    end

    def self.search(search)
        if search
            gamegenre = Gamegenre.find_by(title: search)
            if gamegenre 
                self.where(id: gamegenre)
            else
                Gamegenre.all
            end
        else
            Gamegenre.all
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gamegenres_controller.rb
class GamegenresController < ApplicationController
  before_action :set_gamegenre, only: [:show, :edit, :update, :destroy]

  # GET /gamegenres
  # GET /gamegenres.json
  def index
    @header_classes = {'Title': '', 'Difficulty': '', 'Description': ''}
    @header_classes[params[:sort]] = 'hilite'
    @gamegenres = Gamegenre.all.order(params[:sort])
    @gamegenres = Gamegenre.search(params[:search])
  end

  # GET /gamegenres/1
  # GET /gamegenres/1.json
  def show
    id = params[:id]
    @gamegenre = Gamegenre.find(id)
  end

  # GET /gamegenres/new
  def new
    @gamegenre = Gamegenre.new
  end

  # GET /gamegenres/1/edit
  def edit
  end

  # POST /gamegenres
  # POST /gamegenres.json
  def create
    @gamegenre = Gamegenre.new(gamegenre_params)

    respond_to do |format|
      if @gamegenre.save
        format.html { redirect_to @gamegenre, notice: 'Gamegenre was successfully created.' }
        format.json { render :show, status: :created, location: @gamegenre }
      else
        format.html { render :new }
        format.json { render json: @gamegenre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamegenres/1
  # PATCH/PUT /gamegenres/1.json
  def update
    respond_to do |format|
      if @gamegenre.update(gamegenre_params)
        format.html { redirect_to @gamegenre, notice: 'Gamegenre was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamegenre }
      else
        format.html { render :edit }
        format.json { render json: @gamegenre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamegenres/1
  # DELETE /gamegenres/1.json
  def destroy
    @gamegenre.destroy
    respond_to do |format|
      format.html { redirect_to gamegenres_url, notice: 'Gamegenre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_genres
    @gamegenre = Gamegenre.find(params[:id])

    if @gamegenre.title.empty?
        @gamegenres = Array.new
        flash[:notice] = "'#{@gamegenre.title}' has no title info"
        redirect_to ("/gamegenres") and return
    else
        @gamegenres = Gamegenre.same_genre(@gamegenre.title)
    end
  end

  def search  
    @parameter = params[:search]

    # check if it is an empty string
    if @gamegenre.eql? [""] or @parameter.nil?
      @gamegenres = Array.new
      flash[:notice] = "Empty Search add a genre"
      redirect_to ("/gamegenres")
    else 
        @gamegenres = Gamegenre.same_genre(@gamegenre)
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamegenre
      @gamegenre = Gamegenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamegenre_params
      params.require(:gamegenre).permit(:title, :difficulty, :description, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gamegenres/_form.html.erb
<%= form_for(@gamegenre) do |f| %>
  <% if @gamegenre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamegenre.errors.count, "error") %> prohibited this gamegenre from being saved:</h2>

      <ul>
      <% @gamegenre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamegenres/edit.html.erb
<h1>Editing Game Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamegenre %> |
<%= link_to 'Back', gamegenres_path %>

app/views/gamegenres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gamegenres</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Difficulty</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamegenres.each do |gamegenre| %>
      <tr>
        <td><%= gamegenre.title %></td>
        <td><%= gamegenre.difficulty %></td>
        <td><%= gamegenre.description %></td>
        <td><%= link_to 'Show', gamegenre %></td>
        <td><%= link_to 'Edit', edit_gamegenre_path(gamegenre) %></td>
        <td><%= link_to 'Destroy', gamegenre_path(gamegenre), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Gamegenre', new_gamegenre_path %>
<br>
<br>
<br>
<h4> Search By Genre:</h4>
    <%= form_tag(gamegenres_path, :method => :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Search") %>
    <% end %>

    <% @gamegenres.each do |gamegenre| %>
        <ul>
            <li><%= link_to gamegenre.title, gamegenre_path(gamegenre) %></li><br>
        </ul>
    <% end %>
<br>

app/views/gamegenres/new.html.erb
<h1>New Gamegenre</h1>

<%= render 'form' %>

<%= link_to 'Back', gamegenres_path %>

app/views/gamegenres/search.html.erb
<h1>Search Gamegenres</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Difficulty</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamegenres.each do |gamegenre| %>
      <tr>
        <td><%= gamegenre.title %></td>
        <td><%= gamegenre.difficulty %></td>
        <td><%= gamegenre.description %></td>
        <td><%= link_to 'Show', gamegenre %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gamegenres/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Show Game Genre</h3>
<p>
  <strong>Title:</strong>
  <%= @gamegenre.title %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @gamegenre.difficulty %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gamegenre.description %>
</p>

<%= link_to 'Edit', edit_gamegenre_path(@gamegenre) %> |
<%= link_to 'Back', gamegenres_path %>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %link(rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous")
    %title Game Genres
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %body
      %div.container
        %div.navbar.navbar-expand-lg.bg-primary.text-white
          %h1.title Game Genres
        #main
          - if flash[:notice]
            %div.alert.alert-danger
              #notice.message= flash[:notice]
          - elsif flash[:warning]
            %div.alert.alert-danger
              #warning.message= flash[:warning]

          = yield